# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    test = "test14"
    default_disktype = "Standard"
    default_box = "generic/ubuntu1804"

    config.vm.box_check_update = true

    machines=[ {
        :hostname => "#{test}-server",
        :ip => "192.168.56.10",
        :disk => 2,
        :disksize => 10,
        :disktype => "#{default_disktype}",
        :memory => 1024,
        :cpu => 2,
        :script => "install.sh"
        }, {
        :hostname => "#{test}-client",
        :ip => "192.168.56.100",
        :box => "generic/ubuntu2004",
        :memory => 512,
        :cpu => 1,
        :shell => "apt update"
        }
    ]

    machines.each do |machine|
        config.vm.define machine[:hostname] do |node|
            if (machine[:box].is_a?String)
                node.vm.box = machine[:box]
            else
                node.vm.box = default_box
            end
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip], auto_config: true, virtualbox_intnet: true
            node.vm.provision "shell", path: "#{machine[:script]}" unless not machine [:script].is_a?(String)
            node.vm.provision "shell", inline: "#{machine[:shell]}" unless not machine [:shell].is_a?(String)
            node.vm.provider "virtualbox" do |vbox|
                vbox.name = machine[:hostname]
                vbox.linked_clone = true
                vbox.default_nic_type = "virtio"
                vbox.memory = machine[:memory]
                vbox.cpus = machine[:cpu]
                if (machine[:disk].is_a?Integer and machine[:disk] >= 1)
                    vbox.customize ['storagectl', :id, '--name', 'Virtual I/O Device SCSI controller', '--add', 'virtio-scsi', '--portcount', machine[:disk]]
                    (1..machine[:disk]).each do |disk|
                        disk_file = "#{test}-#{disk}.vdi"
                        vbox.customize ['createhd', '--filename', disk_file, '--variant', machine[:disktype], '--size', machine[:disksize]*1024] unless File.exists?(disk_file)
                        vbox.customize ['storageattach', :id, '--storagectl', 'Virtual I/O Device SCSI controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', disk_file]
                    end
                end
            end
        end
    end
end