# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    # hostname setting
    test = "test05"
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "#{test}"
    # linked clone
    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "#{test}"
        vbox.linked_clone = true
        # simulating virtio on nat
        vbox.default_nic_type = "virtio"
        # cpu and memoria limit
        vbox.memory = 1024
        vbox.cpus = 1
    end
    # run a shell script from an external file
    config.vm.provision "shell", path: "./provision.sh"
  end