# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.provider "virtualbox" do |vbox|
        # linked clone
        vbox.linked_clone = true
    end
  end