# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    # hostname setting
    test = "test09"
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "#{test}"
    # linked clone
    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "#{test}"
        vbox.linked_clone = true
        # simulating virtio on nat
        vbox.default_nic_type = "virtio"
        # cpu and memoria limit
        vbox.memory = 1024
        vbox.cpus = 1
        # add disk
        disk_file = "#{test}.vdi"
        vbox.customize ['storagectl', :id, '--name', 'Virtual I/O Device SCSI controller', '--add', 'virtio-scsi', '--portcount', 4]
        vbox.customize ['createhd', '--filename', disk_file, '--variant', "Standard", '--size', 10*1024] unless File.exists?(disk_file)
        vbox.customize ['storageattach', :id, '--storagectl', 'Virtual I/O Device SCSI controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk_file]
    end
    # run an inline shell script
    config.vm.provision "shell", inline: "apt-get update && apt-get -y install nginx zfsutils && zpool create -m /srv/ srv /dev/sda"
    # port forwarding
    config.vm.network :forwarded_port, guest: 80, host: 9980
    # mount folder
    config.vm.synced_folder ".", "/var/www/html", SharedFoldersEnableSymlinksCreate: false, disabled: false
    # private network
    config.vm.network "private_network", ip: "192.168.56.10", auto_config: true, virtualbox_intnet: true
  end