# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    test = "test12"

    config.vm.box = "generic/ubuntu1804"
    config.vm.box_check_update = true
    config.vm.provision "shell", inline: "apt-get update && apt-get -y install nginx"

    machines=[ {
        :hostname => "#{test}-server",
        :ip => "192.168.56.10"
        }, {
        :hostname => "#{test}-client",
        :ip => "192.168.56.100"
        }
    ]

    machines.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip], auto_config: true, virtualbox_intnet: true
            node.vm.provider "virtualbox" do |vbox|
                vbox.name = machine[:hostname]
                vbox.linked_clone = true
                vbox.default_nic_type = "virtio"
                vbox.memory = 1024
                vbox.cpus = 1
            end
        end
    end
end