# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    # hostname setting
    test = "test08"
    config.vm.box = "generic/ubuntu1804"
    config.vm.hostname = "#{test}"
    # linked clone
    config.vm.provider "virtualbox" do |vbox|
        vbox.name = "#{test}"
        vbox.linked_clone = true
        # simulating virtio on nat
        vbox.default_nic_type = "virtio"
        # cpu and memoria limit
        vbox.memory = 1024
        vbox.cpus = 1
    end
    # run an inline shell script
    config.vm.provision "shell", inline: "apt-get update && apt-get -y install nginx"
    # port forwarding
    config.vm.network :forwarded_port, guest: 80, host: 9980
    # mount folder
    config.vm.synced_folder ".", "/var/www/html", SharedFoldersEnableSymlinksCreate: false, disabled: false
    # private network
    config.vm.network "private_network", ip: "192.168.56.10", auto_config: true, virtualbox_intnet: true
  end