# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    test = "test13"
    default_disktype = "Standard"

    config.vm.box = "generic/ubuntu1804"
    config.vm.box_check_update = true
    config.vm.provision "shell", inline: "apt-get update && apt-get -y install nginx"

    machines=[ {
        :hostname => "#{test}-server",
        :ip => "192.168.56.10",
        :disk => 2,
        :disksize => 10,
        :disktype => "#{default_disktype}"
        }, {
        :hostname => "#{test}-client",
        :ip => "192.168.56.100"
        }
    ]

    machines.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip], auto_config: true, virtualbox_intnet: true
            node.vm.provider "virtualbox" do |vbox|
                vbox.name = machine[:hostname]
                vbox.linked_clone = true
                vbox.default_nic_type = "virtio"
                vbox.memory = 1024
                vbox.cpus = 1
                if (machine[:disk].is_a?Integer and machine[:disk] >= 1)
                    vbox.customize ['storagectl', :id, '--name', 'Virtual I/O Device SCSI controller', '--add', 'virtio-scsi', '--portcount', machine[:disk]]
                    (1..machine[:disk]).each do |disk|
                        disk_file = "#{test}-#{disk}.vdi"
                        vbox.customize ['createhd', '--filename', disk_file, '--variant', machine[:disktype], '--size', machine[:disksize]*1024] unless File.exists?(disk_file)
                        vbox.customize ['storageattach', :id, '--storagectl', 'Virtual I/O Device SCSI controller', '--port', disk, '--device', 0, '--type', 'hdd', '--medium', disk_file]
                    end
                end
            end
        end
    end
end