# -*- mode: ruby -*
# vi: set ft=ruby

Vagrant.configure("2") do |config|
    # hostname setting
    test = "test10"
    config.vm.define "#{test}-server" do |node|
        node.vm.box = "generic/ubuntu1804"
        node.vm.hostname = "#{test}-server"
        # linked clone
        node.vm.provider "virtualbox" do |vbox|
            vbox.name = "#{test}-server"
            vbox.linked_clone = true
            # simulating virtio on nat
            vbox.default_nic_type = "virtio"
            # cpu and memoria limit
            vbox.memory = 1024
            vbox.cpus = 1
            # add disk
            disk_file = "#{test}.vdi"
            vbox.customize ['storagectl', :id, '--name', 'Virtual I/O Device SCSI controller', '--add', 'virtio-scsi', '--portcount', 4]
            vbox.customize ['createhd', '--filename', disk_file, '--variant', "Standard", '--size', 10*1024] unless File.exists?(disk_file)
            vbox.customize ['storageattach', :id, '--storagectl', 'Virtual I/O Device SCSI controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk_file]
        end
        # run an inline shell script
        node.vm.provision "shell", inline: "apt-get update && apt-get -y install nginx zfsutils && zpool create -m /srv/ srv /dev/sda"
        # port forwarding
        node.vm.network :forwarded_port, guest: 80, host: 9980
        # mount folder
        node.vm.synced_folder ".", "/var/www/html", SharedFoldersEnableSymlinksCreate: false, disabled: false
        # private network
        node.vm.network "private_network", ip: "192.168.56.10", auto_config: true, virtualbox_intnet: true
    end

    config.vm.define "#{test}-client", primary: true do |node| # automated ssh login
        node.vm.box = "generic/ubuntu1804"
        node.vm.hostname = "#{test}-client"
        node.vm.provider "virtualbox" do |vbox|
            vbox.name = "#{test}-client"
            vbox.linked_clone = true
            vbox.default_nic_type = "virtio"
            vbox.memory = 512
            vbox.cpus = 1
        end
        node.vm.provision "shell", inline: "apt-get update"
        node.vm.network "private_network", ip: "192.168.56.10", auto_config: true, virtualbox_intnet: true
    end
  end